### ISSUE TITLE
Orion-CRC: Original H&E Images Data Access

### ISSUE THREAD

**Issue by eshasadia** [labsyspharm/orion-crc#10]
While accessing the Orion-CRC data through the S3 buckets, I was able to locate the registered H&E and OME-TIFF images. However, I wanted to inquire if it's possible to access the original H&E images as well. If so, could you kindly provide the link to these images?

**Comment by jrlin1001** [comment]
Dear Esha,

Sorry we don't have the original H&E images at this moment due to some patient-identity related issues.  We will let you know once these images become available.  Apologize for the inconvenience.  

Best,
-jerry-
