### ISSUE TITLE
Argo550

### ISSUE THREAD

**Issue by calm-focus** [labsyspharm/orion-crc#8]
Could you please tell me the meaning of Argo550 in the marker.csv or p37_s29_a24_c59kx_e15__at__20220106_014304_946511_cellringmask.csv?

**Comment by jrlin1001** [comment]
Hi calm-focus, Argo550 is an empty channel in our panel.  You can ignore that in your analysis.

**Comment by calm-focus** [comment]
@jrlin1001 Thank you for your promp reply! 
Are both segmentation masks (*-mask.ome.tif) in Aws s3 and nuclear segmentation mentioned in the paper derived from IF images rather than H&E images?

**Comment by jrlin1001** [comment]
Yes, all segmentation masks were derived from IF/Orion images.
