### ISSUE TITLE
Resolution for H&E images

### ISSUE THREAD

**Issue by cacof1** [labsyspharm/orion-crc#9]
We've been analysis these data for the last year and I have a question which you may help me answer.

The data on the ORION-CRC are supposedly scanned on the Leica Aperios 450 GT which has a slide resolution of 0.26 um/pix at 40x.

The slides downloaded from the AWS S3 have a resolution of [1,1] with no units. I suspect it's due to the registration software PALOM.

The IF slides have a resolution of [0.325,0.325] um/pix and seems to be co-registered to the H&E images. 

Am I to understand that the H&E resolution was downgraded to 0.325/0.325 to match that of the IF?

Thanks a lot

**Comment by jrlin1001** [comment]
The images we provided are registered images with adjusted resolution in order to matched the fluorescence images.  So yes it's different from acquired resolution (0.26 um)
